export const MAJOR_OPTIONS = [
  { value: 'cntt', label: 'Công nghệ thông tin (CNTT)' },
  { value: 'udpm', label: 'Ứng dụng phần mềm (UDPM)' },
  { value: 'lttbdd', label: 'Lập trình thiết bị di động' },
  { value: 'tkdh', label: 'Thiết kế đồ hoạ' },
  { value: 'tkweb', label: 'Thiết kế website' },
  { value: 'mmt', label: 'Mạng máy tính (MMT)' },
  { value: 'qtdn', label: 'Quản trị doanh nghiệp' },
  { value: 'tmdt', label: 'Thương mại điện tử' },
  { value: 'other', label: 'Khác...' },
] as const;

export const TARGET_ROLE_OPTIONS = [
  { value: 'frontend', label: 'Frontend Developer' },
  { value: 'backend', label: 'Backend Developer' },
  { value: 'fullstack', label: 'Fullstack Developer' },
  { value: 'mobile', label: 'Mobile Developer' },
  { value: 'devops', label: 'DevOps Engineer' },
  { value: 'data', label: 'Data Engineer / Analyst' },
  { value: 'qa', label: 'QA / Tester' },
  { value: 'uiux', label: 'UI/UX Designer' },
  { value: 'other', label: 'Khác...' },
] as const;

export const EDUCATION_YEARS_OPTIONS = [
  { value: '1', label: 'Năm 1' },
  { value: '2', label: 'Năm 2' },
  { value: '3', label: 'Năm 3' },
  { value: '4', label: 'Năm 4' },
  { value: 'graduated', label: 'Đã tốt nghiệp' },
] as const;

export const VIETNAM_UNIVERSITIES: string[] = [
  'FPT Polytechnic',
  'Cao đẳng FPT Polytechnic Hà Nội',
  'Cao đẳng FPT Polytechnic TP.HCM',
  'Cao đẳng FPT Polytechnic Đà Nẵng',
  'Cao đẳng FPT Polytechnic Cần Thơ',
  'Trường Đại học FPT',
  'Đại học Quốc gia Hà Nội',
  'Đại học Quốc gia TP.HCM',
  'Đại học Bách Khoa Hà Nội',
  'Trường Đại học Bách Khoa - ĐHQG TP.HCM',
  'Trường Đại học Bách Khoa - ĐH Đà Nẵng',
  'Đại học Kinh tế Quốc dân',
  'Trường Đại học Kinh tế TP.HCM',
  'Trường Đại học Kinh tế - ĐH Đà Nẵng',
  'Đại học Sư phạm Hà Nội',
  'Đại học Sư phạm TP.HCM',
  'Đại học Sư phạm Kỹ thuật TP.HCM',
  'Đại học Khoa học Tự nhiên - ĐHQGHN',
  'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQGHN',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM',
  'Đại học Công nghệ - ĐHQGHN',
  'Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
  'Đại học Quốc tế - ĐHQG TP.HCM',
  'Đại học Kinh tế - Luật - ĐHQG TP.HCM',
  'Đại học Công nghiệp TP.HCM',
  'Đại học Công nghệ TP.HCM (HUTECH)',
  'Đại học Tôn Đức Thắng',
  'Đại học Nguyễn Tất Thành',
  'Đại học Mở TP.HCM',
  'Đại học Văn Lang',
  'Đại học Hoa Sen',
  'Đại học Tài chính - Marketing',
  'Đại học Ngoại Thương',
  'Đại học Luật Hà Nội',
  'Đại học Thương mại',
  'Đại học Giao thông Vận tải',
  'Đại học Xây dựng',
  'Đại học Thủy lợi',
  'Đại học Mỏ - Địa chất',
  'Đại học Điện lực',
  'Học viện Tài chính',
  'Học viện Ngân hàng',
  'Học viện Công nghệ Bưu chính Viễn thông',
  'Đại học Duy Tân',
  'Đại học Đà Nẵng',
  'Đại học Huế',
  'Đại học Cần Thơ',
  'Đại học An Giang',
  'Đại học Nha Trang',
  'Đại học Nông Lâm TP.HCM',
  'Đại học Lâm nghiệp',
  'Đại học Y Hà Nội',
  'Đại học Y Dược TP.HCM',
  'Học viện Kỹ thuật Mật mã',
  'RMIT Vietnam',
  'VinUniversity',
  'British University Vietnam',
];
